### ISSUE TITLE
Add a "terminal" CSS Class

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/container-immersion#18]
Add a "terminal" css class to render fixed-width samples like a terminal.

The terminal style should have a black background with a bright green font.

Apply the terminal class in _labs/*.md where we are simulating a terminal (wrapped with \`\`\`). We should be able to do something like this to selectively apply the class: http://digitaldrummerj.me/styling-jekyll-markdown/

If possible, leave the class off items that are not supposed to be a terminal (like HTML samples).

**Comment by monsij** [comment]
Hello there,is there a time restriction to complete it?Like say 2hours or so?

**Comment by daviddeejjames** [comment]
Happy to give this one a shot if @monsij doesn't end up taking the challenge 😉

**Comment by monsij** [comment]
Ok so can anyone tell me do I just have to define the terminal css class?And also where shall i add this piece of code,in a separate file or update an existing one?

**Comment by daviddeejjames** [comment]
@monsij it would be a matter of adding this class to a css file and ensuring it works using the Jekyll markdown as per the description

**Comment by monsij** [comment]
Thanks, got it finally.Time to give it a try!

**Comment by mkasberg** [comment]
CSS is at `assets/css/immersion.scss`. Probably add a `terminal` class there and then update the markdown in `_labs/*.md` to see it in action.

The site is done in Jekyll; see README.md for help getting it running locally.
