### ISSUE TITLE
Responsive Improvements

### ISSUE THREAD

**Issue by daviddeejjames** [mkasberg/container-immersion#19]
Would love to help out on this project, few minor improvements I can see for in terms of responsive design.
For example, the 'Fork Me On Github' banner is great, but kinda covers the menu on mobile devices.

Just wondering if you intend this site to be viewable on mobile and tablet devices, and you would like me to help with a few small CSS tweaks in regards to this 😄

**Comment by mkasberg** [comment]
Yeah, I've also noticed the issure you're referring to with the github banner.

Any improvements you could make would be great! Feel free to open up a pull request. Ideally, the site will look good on both desktop and mobile.

**Comment by mkasberg** [comment]
Fixed by #20.
