### ISSUE TITLE
Contribute to Container Immersion for Hacktoberfest 2017

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/container-immersion#2]
You can help improve Container Immersion for [Hacktoberfest 2017](https://hacktoberfest.digitalocean.com/)!

Ideas for contributing:

- Minor improvements to existing labs. (Updated commands, additional tips, etc.)
  - Ex. 20baee251097edfef4ed9f4b491b8932dff4ca05
- Create a new lab (HTML page for Docker tutorial).
  - Consider any content that seems missing, but would be useful for beginners and fit at the same relative level of difficulty as the current labs.
- Improve the Look & Feel of the site.
  - Keep it simple & don't take it in a completely new direction.
- Fix minor bugs & typos.

Feel free to comment below if you want additional guidance or suggestions!

**Comment by wildan3105** [comment]
Hi, just arrived here. I feel that the explanation at homepage has very large font and the position of `footer` is a little bit strange. Can I fix that up regarding of this issue?

**Comment by mkasberg** [comment]
That sounds like a welcome change. Give it a shot!

**Comment by wildan3105** [comment]
Alright!

**Comment by mkasberg** [comment]
Remember to wait 'til tomorrow to open your pull request if you want it to count for Hacktoberfest!

**Comment by wildan3105** [comment]
Okay. In my timezone (Indonesia), it's already October 1st though :smiley:

**Comment by wildan3105** [comment]
Hi, just quick question. In order to edit the homepage, I need to un-ignore the `_site` folder. Is that acceptable? Thanks

**Comment by mkasberg** [comment]
The site is generated using [Jekyll](http://jekyllrb.com/docs/home/). Don't un-ignore the _site folder - that's just the generated content.

You should make your changes in either `_layouts` or `_includes`. After making your changes, `bundle exec jekyll serve` will re-generate the site in `_site` so you can see them.

If you've already got a change that you like in the `_site` folder, you can probably search for the text inside the `_layouts` or `_includes` folder and make the same change there.

**Comment by wildan3105** [comment]
Okay, got that :ok_hand:

**Comment by mkasberg** [comment]
@wildan3105 I like the style changes, but you need to make the change in `assets/css/immersion.css` rather than using inline styles. I left a comment on you commit explaining a little more. Feel free to open a pull request with your improvements.

**Comment by wildan3105** [comment]
okay will do that

**Comment by mkasberg** [comment]
@wildan3105 I opened #8 to account for the changes you're working on. Let's move discussion of those changes over to that thread.

**Comment by wildan3105** [comment]
Alright
