### ISSUE TITLE
Create a Favicon for Container Immersion

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/container-immersion#22]
Create a Favicon for the site.

The favicon should be called `favicon.ico` and live in the project root. If you're not familiar with favicons, you can read way more than you ever wanted to know about them here: https://github.com/audreyr/favicon-cheat-sheet. I don't care too much about larger icons for mobile - just a 16x16/32x32 favicon.ico would be sufficient for now. But feel free to add additional formats if you want.

I think some kind of whale would be appropriate, but you could get creative if you want. Also, since this will be an image, make sure you don't use anything that would violate someone's copyright. Using something from an existing icon set would be fine as long as it's licensed to be used in open source projects.

**Comment by Seanland** [comment]
Hi @mkasberg can I attempt this.  (forewarning this would be my first open source contribution :D )

**Comment by mkasberg** [comment]
Hi Sean,

Thanks for the response. How exciting to make your first contribution!

Yeah, give it a shot, and feel free to post here if you have questions along the way - I'll try to help.

**Comment by Seanland** [comment]
Great! I will do what I can.  BTW, this project looks great and I hope to contribute to it in the future!

**Comment by Seanland** [comment]
#24 has been submitted.

**Comment by mkasberg** [comment]
Looks great Sean! Nice work.

**Comment by mkasberg** [comment]
@Seanland Do you have a higher-res version of that icon, or would you like to create one?

I think it would probably look good on the homepage somewhere near the title :)

**Comment by Seanland** [comment]
@mkasberg Yeah, its ~500 x ~500.  It should be able to make a decently small logo somewhere.  I will play around and see what I can come up with!

**Comment by mkasberg** [comment]
Upon closer inspection, I don't think we can use that logo. Although https://www.shareicon.net/media-logo-social-docker-878789 marks it as free for commercial use, I think they just copied it from Docker:

![logocomparison](https://user-images.githubusercontent.com/12214617/31745318-7587a50a-b41f-11e7-85ad-c0831215a142.png)

It's a little too similar for me to be comfortable using it since the official Docker image is trademarked.

An alternative possibility is the spouting whale from Twemoji, which is licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) and is free to "remix, transform, and build upon the material for any purpose, even commercially." - we need to give attribution if we use it, probably in the form of a link at the bottom of the homepage and/or readme. We could potentially change colors, maybe change the water to a single container block, etc.

https://github.com/twitter/twemoji/blob/gh-pages/72x72/1f433.png
https://github.com/twitter/twemoji/blob/gh-pages/svg/1f433.svg

**Comment by Seanland** [comment]
Hey @mkasberg, If you think it is a good idea to change the image I am totally fine with that.  I would rather not step on any toes even if there is a chance.   

Should I modify the favicon based on this decision also?

**Comment by mkasberg** [comment]
Yes, please do. I reverted the original favicon commit from a couple of days ago, so you have a clean slate right now to try whatever you'd like.

Sorry we couldn't use your original work; thanks for giving it another shot! :+1:

**Comment by Seanland** [comment]
@mkasberg I will gladly add the licensing requirements (I did not yet, in those two pull requests).

I was wondering if you could supply me with the proper verbiage?

**Comment by mkasberg** [comment]
Something like this would be good:

Logo based on whale emoji from [Twemoji](https://github.com/twitter/twemoji) (licensed under [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/)).

Thanks!
