### ISSUE TITLE
Add License Info to the Homepage

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/container-immersion#25]
Container Immersion is licensed under the MIT license. We should mention this on the homepage.

Add text near the bottom of the homepage (below the link to Git Immersion) to say "Container Immersion is free to use and modify under the MIT License". "MIT License" should link to https://github.com/mkasberg/container-immersion/blob/master/LICENSE.

The file you need to edit to do this is `_layouts/index.html`.

**Comment by agdhruv** [comment]
I'll take this!
