### ISSUE TITLE
Main Page Logo Placement

### ISSUE THREAD

**Issue by Seanland** [mkasberg/container-immersion#35]
An image has been uploaded to /assets/img/docker_front_page.png

Attempt to find a place on the index page.

**Comment by mkasberg** [comment]
If you're new to the project, feel free to take a stab at this one. Keep in mind that we're using Bootstrap and Jekyll - see the readme if you're unfamiliar with the development workflow.

The logo could go anywhere on the homepage where it looks good, but it should not bump content too far down - the "Begin Immersion" link near the bottom should remain visible without scrolling on a desktop-sized screen.

**Comment by tshiamobhuda** [comment]
I'd like to work on this :smiley:

**Comment by schalkneethling** [comment]
@TremaineNeethling, here is one for you.

**Comment by TremaineNeethling** [comment]
@Seanland, working on it

**Comment by TremaineNeethling** [comment]
@mkasberg, added the logo to the landing page. see screenshot below, let me know if this works for you.

![fireshot capture 1 - container immersion - http___localhost_4000_container-immersion_](https://user-images.githubusercontent.com/23447760/32137198-79624fc8-bc1b-11e7-8dd0-adeb1d52e852.png)
