### ISSUE TITLE
Increase TOC font size

### ISSUE THREAD

**Issue by mkasberg** [mkasberg/container-immersion#9]
The font size in the table of contents appears to small. We should make that a little bigger so it's easier to read. Perhaps also space out the items a little.

The TOC: https://mkasberg.github.io/container-immersion/toc.html

**Tips**
 - Since these are style changes, you should make them in `assets/css/immersion.scss`.
 - You may need to add a class to one of the divs in `layouts/toc.html` to apply your style specifically to the TOC without modifying other parts of the site.
- Modifying other parts of the site (for example, make text slightly larger everywhere) is also acceptable as long as it looks good.

**Comment by cpdevelops** [comment]
I'll get to work on this. Should see a PR from me soon.

**Comment by ShubhMisaki** [comment]
Working on This !!

**Comment by rishabhnehra** [comment]
Can I give it a try ?
